import React from "react";
import { Descriptions, Divider } from "antd";
import "./Introduction.less";
const Introduction = () => (
  <div className="intro-container">
    {/* Geolife */}

    <h1 id="/dataset/#geolife">GeoLife</h1>
    <h2 id="/dataset/#geolife-intro">Introduction</h2>
    <p>
      Geolife is a real-world dataset which contains GPS vehicle trajectories of
      182 users over 5 years published by Microsoft. We limit the location range
      to Beijing, China and filter outliers. The dataset contains 14,650
      trajectories.
    </p>
    <h2 id="/dataset/#geolife-ref">References</h2>
    <Descriptions bordered>
      <Descriptions.Item span={3} label="author">
        Yu Zheng and Lizhu Zhang and Xing Xie and Wei-Ying Ma
      </Descriptions.Item>
      <Descriptions.Item span={3} label="editor">
        Juan Quemada and Gonzalo Le'on and Yo"elle S. Maarek and Wolfgang Nejdl
      </Descriptions.Item>
      <Descriptions.Item span={3} label="title">
        Mining interesting locations and travel sequences from GPS trajectories
      </Descriptions.Item>
      <Descriptions.Item span={3} label="booktitle">
        Proceedings of the 18th International Conference on World Wide Web, WWW
        2009, Madrid, Spain, April 20-24, 2009
      </Descriptions.Item>
      <Descriptions.Item span={3} label="pages">
        791--800
      </Descriptions.Item>
      <Descriptions.Item span={3} label="publisher">
        2009
      </Descriptions.Item>
      <Descriptions.Item span={3} label="url">
        <a href="https://doi.org/10.1145/1526709.1526816">
          https://doi.org/10.1145/1526709.1526816
        </a>
      </Descriptions.Item>
      <Descriptions.Item span={3} label="doi">
        10.1145/1526709.1526816
      </Descriptions.Item>
      <Descriptions.Item span={3} label="timestamp">
        Tue, 06 Nov 2018 16:57:07 +0100
      </Descriptions.Item>
      <Descriptions.Item span={3} label="biburl">
        <a href="https://dblp.org/rec/conf/www/ZhengZXM09.bib">
          https://dblp.org/rec/conf/www/ZhengZXM09.bib
        </a>
      </Descriptions.Item>
      <Descriptions.Item span={3} label="bibsource">
        dblp computer science bibliography,{" "}
        <a href="https://dblp.org">https://dblp.org</a>
      </Descriptions.Item>
    </Descriptions>
    <h2 id="/dataset/#geolife-link">Data Link</h2>
    <Descriptions bordered>
      <Descriptions.Item span={3} label="original">
        <a href="https://www.microsoft.com/en-us/research/project/geolife-building-social-networks-using-human-location-history/">
          https://www.microsoft.com/en-us/research/project/geolife-building-social-networks-using-human-location-history/
        </a>
      </Descriptions.Item>
      {/* <Descriptions.Item span={3} label="cleaned">
        <a href=""></a>
      </Descriptions.Item> */}
    </Descriptions>

    {/* Brinkhoff */}

    <h1 id="/dataset/#brinkhoff">Brinkhoff</h1>
    <h2 id="/dataset/#brinkhoff-intro">Introduction</h2>
    <p>
      Brinkhoff is a simulated dataset generated by Brinkhoff's network
      generator. The Brinkhoff dataset we used contains 50,000 trajectories
      located in Oldenburg, Germany.
    </p>
    <h2 id="/dataset/#brinkhoff-ref">References</h2>
    <Descriptions bordered>
      <Descriptions.Item span={3} label="article">
        DBLP:journals/geoinformatica/Brinkhoff02
      </Descriptions.Item>
      <Descriptions.Item span={3} label="author">
        Thomas Brinkhoff
      </Descriptions.Item>
      <Descriptions.Item span={3} label="title">
        A Framework for Generating Network-Based Moving Objects
      </Descriptions.Item>
      <Descriptions.Item span={3} label="journal">
        GeoInformatica
      </Descriptions.Item>
      <Descriptions.Item span={3} label="volume">
        6
      </Descriptions.Item>
      <Descriptions.Item span={3} label="number">
        2
      </Descriptions.Item>
      <Descriptions.Item span={3} label="pages">
        153--180
      </Descriptions.Item>
      <Descriptions.Item span={3} label="year">
        2002
      </Descriptions.Item>
      <Descriptions.Item span={3} label="url">
        <a href="https://doi.org/10.1023/A:1015231126594">
          https://doi.org/10.1023/A:1015231126594
        </a>
      </Descriptions.Item>
      <Descriptions.Item span={3} label="doi">
        10.1023/A:1015231126594
      </Descriptions.Item>
      <Descriptions.Item span={3} label="timestamp">
        Sun, 28 May 2017 13:19:56 +0200
      </Descriptions.Item>
      <Descriptions.Item span={3} label="biburl">
        <a href="https://dblp.org/rec/journals/geoinformatica/Brinkhoff02.bib">
          https://dblp.org/rec/journals/geoinformatica/Brinkhoff02.bib
        </a>
      </Descriptions.Item>
      <Descriptions.Item span={3} label="bibsource">
        dblp computer science bibliography,
        <a href="https://dblp.org">https://dblp.org</a>
      </Descriptions.Item>
    </Descriptions>
    <h2 id="/dataset/#brinkhoff-link">Data Link</h2>
    <Descriptions bordered>
      <Descriptions.Item span={3} label="original">
        <a href="https://iapg.jade-hs.de/personen/brinkhoff/generator/">
          https://iapg.jade-hs.de/personen/brinkhoff/generator/
        </a>
      </Descriptions.Item>
      {/* <Descriptions.Item span={3} label="cleaned">
        <a href=""></a>
      </Descriptions.Item> */}
    </Descriptions>

    {/* GZTaxi */}
    <h1 id="/dataset/#gztaxi">GZTaxi</h1>
    <h2 id="/dataset/#gztaxi-intro">Introduction</h2>
    <p>
      GZTaxi is a real-world dataset which contains 4 billion GPS trajectories
      of nearly 50,000 vehicles from Guangzhou, China in two months.
    </p>
    <h2 id="/dataset/#gztaxi-ref">References</h2>
    <Descriptions bordered>
      <Descriptions.Item span={3} label="article">
        DBLP:journals/tii/XieZLHWYL21
      </Descriptions.Item>
      <Descriptions.Item span={3} label="author">
        Guangqiang Xie and Runpeng Zhang and Yang Li and Ling Huang and
        Chang-Dong Wang and Hao Yang and Jiahao Liang
      </Descriptions.Item>
      <Descriptions.Item span={3} label="title">
        AttractRank: District Attraction Ranking Analysis Based on Taxi Big Data
      </Descriptions.Item>
      <Descriptions.Item span={3} label="journal">
        IEEE Trans. Ind. Informatics
      </Descriptions.Item>
      <Descriptions.Item span={3} label="volume">
        17
      </Descriptions.Item>
      <Descriptions.Item span={3} label="number">
        3
      </Descriptions.Item>
      <Descriptions.Item span={3} label="pages">
        1679--1688
      </Descriptions.Item>
      <Descriptions.Item span={3} label="year">
        2021
      </Descriptions.Item>
      <Descriptions.Item span={3} label="url">
        <a href="https://doi.org/10.1109/TII.2020.2994038">
          https://doi.org/10.1109/TII.2020.2994038
        </a>
      </Descriptions.Item>
      <Descriptions.Item span={3} label="doi">
        10.1109/TII.2020.2994038
      </Descriptions.Item>
      <Descriptions.Item span={3} label="timestamp">
        Tue, 22 Dec 2020 13:54:17 +0100
      </Descriptions.Item>
      <Descriptions.Item span={3} label="biburl">
        <a href="https://dblp.org/rec/journals/tii/XieZLHWYL21.bib">
          https://dblp.org/rec/journals/tii/XieZLHWYL21.bib
        </a>
      </Descriptions.Item>
      <Descriptions.Item span={3} label="bibsource">
        dblp computer science bibliography,
        <a href="https://dblp.org">https://dblp.org</a>
      </Descriptions.Item>
    </Descriptions>
    <br/>
    <br/>
    <br/>
    <Divider orientation="center">Bottom</Divider>
  </div>
);

export default Introduction;
