import {
  LineChartOutlined,
  BoxPlotOutlined,
  HomeOutlined,
  DatabaseOutlined,
} from "@ant-design/icons";

import Statistic from "../views/Statistic/Statistic";
// import Map from "./views/Map/Map";
import DotMap from "../views/DotMap/DotMap";
import Home from "../views/Home/Home";
import Contrast from "../views/Contrast/Contrast";
import Dataset from "../views/Dataset/Dataset";
import Overall from "../views/Overall/Overall";
import LineChart from "../components/LineChart/LineChart";
import GeoLife from "../assets/data/indicators/GeoLife";
import Brinkhoff from "../assets/data/indicators/Brinkhoff";
import gz_30 from "../assets/data/indicators/gz_30";

export const router = [
  {
    key: "home",
    path: "/",
    name: "Home",
    icon: <HomeOutlined />,
    component: Home,
    exact: true,
  },
  {
    key: "dataset",
    path: "/dataset",
    name: "Dataset & Metrics",
    icon: <DatabaseOutlined />,
    component: Dataset,
  },
  {
    key: "statistic/Geolife",
    path: "/statistic/Geolife",
    name: "Statistic",
    icon: <LineChartOutlined />,
    component: Statistic,
  },
  {
    key: "overall",
    path: "/overall",
    name: "Overall Comparison",
    icon: <LineChartOutlined />,
    component: Overall,
  },
  {
    key: "dotMap",
    path: "/dotMap",
    name: "Comparison Of Indices",
    icon: <BoxPlotOutlined />,
    component: DotMap,
  },
  {
    key: "contrast",
    path: "/contrast",
    name: "Algorithm Comparison",
    icon: <BoxPlotOutlined />,
    component: Contrast,
  },
];


export const subRouter = [
  {
    key: "line1",
    path: "/statistic/Geolife",
    icon: <LineChartOutlined />,
    name: "GeoLife",
    component: <LineChart data={GeoLife} title="GeoLife" intro="Geolife is a real-world dataset which contains GPS vehicle trajectories of 182 users over 5 years published by Microsoft. We limit the location range to Beijing, China and filter outliers. The dataset contains 14,650 trajectories."></LineChart>
  },
  {
    key: "line2",
    path: "/statistic/Brinkhoff",
    icon: <LineChartOutlined />,
    name: "Brinkhoff",
    component: <LineChart data={Brinkhoff} title="Brinkhoff" intro="Brinkhoff is a simulated dataset generated by Brinkhoff's network generator. The Brinkhoff dataset we used contains 50,000 trajectories located in Oldenburg, Germany."></LineChart>
  },
  {
    key: "line3",
    path: "/statistic/GuangZhouTaxi_30s",
    icon: <LineChartOutlined />,
    name: "GZTaxi",
    component: <LineChart data={gz_30} title="GZTaxi (~30 seconds)" intro="GZTaxi is a real-world dataset which contains 4 billion GPS trajectories of nearly 50,000 vehicles from Guangzhou, China in two months."></LineChart>
  },
]