import React, { Component } from "react";
import "./Home.less";

class Home extends Component {
  state = {};
  render() {
    return (
      <div className="home-container flex-center">
        <div className="title flex-center">DP-STP</div>
        <div className="abstract">
          &nbsp;&nbsp;&nbsp;&nbsp;<strong>Abstract</strong> - With the rapid
          development of wireless communication and localization technologies,
          the easier collection of trajectory data can bring potential
          data-driven value. In recent years, extensive researches have focused
          on how to publish trajectory data without revealing personal
          information. However, the existing researches have some deficiencies.
          They cannot strike a good balance between data utility and privacy
          protection. In this paper, we propose a probability distribution based
          model named DP-STP (Differentially Private Sequential Trajectory
          Publishing) which satisfies differential privacy while publishing
          sequential trajectory data with high utility. With the same privacy
          budget, the trajectories generated by DP-STP are close to the density
          distribution of the original trajectories, and their statistical
          properties are also similar to the original trajectories.
          First, a
          multilevel adaptive grid is proposed to map trajectories to multilevel
          grids, which makes trajectories more uniformly distributed and less
          disturbed by noise. Second, a direction and density-based
          postprocessing method is designed to solve the problem that the end
          point deviates too much from its predecessor while generating
          trajectories, so that the generated trajectories are smooth. The
          experiments on two benchmark datasets and a real-world taxi dataset in
          Guangzhou, China show that the trajectories generated by DP-STP can
          achieve significantly better data utility while preserving privacy
          than the state-of-art method.
        </div>
      </div>
    );
  }
}

export default Home;
