import React, { Component } from "react";
import "./Home.less";

/**
 * Home
 */
class Home extends Component {
  state = {};
  render() {
    return (
      <div className="home-container flex-center">
        <div className="title flex-center">AWDP</div>
        <div className="abstract">
          &nbsp;&nbsp;&nbsp;&nbsp;<strong>Abstract</strong> - With the rapid
          development of wireless communication and localization technologies,
          the easier collection of trajectory data can bring potential
          data-driven value. In recent years, there has been an increasing
          interest in how to publish trajectory dataset without revealing
          personal information. However, since the large and real-world
          trajectory dataset presents an uneven regional distribution, the
          existing study can not meet the requirements of high privacy
          protection, resulting in lower utility of the published synthetic
          dataset. 
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;In this paper, we propose a probability distribution model
          named AWDP (Adaptive grid-based Weighted Differential Privacy) for
          publishing sequential trajectory dataset with differential privacy
          guarantee and high utility.
          <br /> 
          &nbsp;&nbsp;&nbsp;&nbsp;First, sequential trajectories are
          adaptively and discriminatingly discretized into the multi-resolution
          grid structures with sufficient resolution, which makes trajectories
          more uniformly distributed and less disturbed by noise. Second, the
          regional characteristics are considered to design a weighted
          differential privacy mechanism, in which the weighted budgets are
          allocated in grids according to resolution. Third, a spatio-temporal
          continuity maintenance method is designed to solve unrealistic
          direction- and density-based continuity deviations of synthetic
          trajectories, so that the generated synthetic trajectories are more
          reasonable. 
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;An application system is developed for demonstration
          purposes which is available online at <a href="http://qgailab.com/awdp/">http://qgailab.com/awdp/</a>. 
          <br/>
          &nbsp;&nbsp;&nbsp;&nbsp;The experiments on one simulated dataset and two real-world datasets show
          that the synthetic trajectories generated by AWDP are close to the
          density distribution of the original trajectories. Besides, their
          statistical properties of five metrics are noticeably similar to the
          original trajectories, compared with the state-of-art method DP-Star.
          The remarkable results demonstrate that there exists a significant
          positive correlation between data utility and weighted differential
          privacy.
        </div>
      </div>
    );
  }
}

export default Home;
